### ISSUE TITLE
0.0.4 failing to build on node v0.10.12

### ISSUE THREAD

**Issue by ndrut** [rla/fast-feed#5]
```
npm http 200 https://registry.npmjs.org/fast-feed/-/fast-feed-0.0.4.tgz

> fast-feed@0.0.4 install /home/m/node_modules/fast-feed
> node-gyp rebuild

make: Entering directory `/home/m/node_modules/fast-feed/build'
  CXX(target) Release/obj.target/parser/src/parser.o
../src/parser.cc: In function ‘void parseAtomFeed(rapidxml::xml_node<char>*, const v8::Local<v8::Object>&, bool)’:
../src/parser.cc:119: error: ‘strcmp’ was not declared in this scope
make: *** [Release/obj.target/parser/src/parser.o] Error 1
make: Leaving directory `/home/m/node_modules/fast-feed/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 2.6.32-358.14.1.el6.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/m/node_modules/fast-feed
gyp ERR! node -v v0.10.12
gyp ERR! node-gyp -v v0.9.5
gyp ERR! not ok 
npm ERR! fast-feed@0.0.4 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! 
npm ERR! Failed at the fast-feed@0.0.4 install script.
npm ERR! This is most likely a problem with the fast-feed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls fast-feed
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 2.6.32-358.14.1.el6.x86_64
npm ERR! command "node" "/usr/bin/npm" "install" "fast-feed"
npm ERR! cwd /home/m
npm ERR! node -v v0.10.12
npm ERR! npm -v 1.2.17
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/m/npm-debug.log
npm ERR! not ok code 0
```
